# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09ab2adab33f26c3ca266fc05f202ce0f7a0041f3cf101339516d60a621f51ece4ab240b00095dd38b6230cc59828a152516dd8ac0df61fc698753818925f171

test:
  secret_key_base: 81940a96b54a4720409ea17f36519f7adfebb2711fb2a7ddb1890c4c30181d68cbaa6656710a59782431e25a485a7c159d6e7d02c4ee01a76d80fc036a6d9aa3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
